#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        30_Change_root_password
# Type:        Execute
# Script Type: Shell
# Description: Change the root password for the VM

# Script:

set -ex

echo '@@{rootpassword}@@' | sudo passwd root --stdin
