#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        46b_Distribute_new_hosts_file
# Type:        Execute
# Script Type: Shell
#Description:  distribute the hosts files from vm 0 to all VMs deployed by the
#              blueprint. Would not be necessary if previous script registers
#              VMs to the DNS

# Script:

# ADDRESS ARRAY BUG, LINE 29: # March 2021 16th

# March 2021 16th: Due to a bug, if VM is added as scale out action, th script needs to be run differenty. Therefore
# If the samaphore file does not exist (VM created subsenquently with Scale Out action), calm_array_address is missing
# new VM IP which needs to be added... This has to be removed when the bug is fixed


set -ex

# Get hosts file from vm0
sudo scp -o StrictHostKeyChecking=no @@{calm_array_address[0]}@@:/etc/hosts /etc/

if ! [ -f /home/@@{admin_cred.username}@@/changes/semaphore ]
  then
    # Get VMs IPs
    ips=($(echo "@@{calm_array_address}@@,@@{address}@@" | tr "," " "))

    #Get number of replicas
    nr_of_ips=${#ips[@]}

    # Push hosts file to other VMs
    for index in $(seq 0 $(expr $nr_of_ips - 1))
    do
      case $index in
        0)
          echo "This is the 1st VM. Nothing to do"
        ;;
        @@{calm_array_index}@@)
          echo "This is the current VM. nothing to do"
        ;;
        *)
          sudo scp -o StrictHostKeyChecking=no /etc/hosts ${ips[$index]}:/etc/hosts
        ;;
      esac
    done
fi
# Display hosts file for troubleshooting purpose
cat /etc/hosts
